name: shopify
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  folding_cell: ^1.0.2
  google_fonts: ^2.0.0
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.7.4
  firebase_storage: ^8.0.2
  flutter_staggered_grid_view: ^0.3.4
  path_provider: ^2.0.1
  image: ^3.0.2
  cloudinary_public: ^0.8.1+1
  dio: ^4.0.0
  image_slider: ^1.0.2
  fluttertoast: ^8.0.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/deelogo.png






# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
    - assets/Totebag.jpg
    - assets/nike.jpg
    - assets/adidas.jpg
    - assets/deelogo.png

  fonts:
    - family: signatra
      fonts:
        - asset: assets/signatra.ttf
    - family: Love
      fonts:
        - asset: assets/Love.ttf
